install:
  - "gem install bundler -v 1.9.5"
  - "travis_retry bundle install --jobs=3 --retry=3"
  - "bundle exec rake neo4j:install[community-$NEO4J_VERSION]"
  - "echo 'dbms.memory.pagecache.size=1g' >> ./db/neo4j/development/conf/neo4j.conf"
  - "echo 'dbms.memory.heap.max_size=1000' >> ./db/neo4j/development/conf/neo4j-wrapper.conf"
  - "echo 'dbms.memory.heap.initial_size=1000' >> ./db/neo4j/development/conf/neo4j-wrapper.conf"
  - "bundle exec rake neo4j_spatial:install"
  - "bundle exec rake neo4j:start --trace"
  - "sleep 20"
sudo: false
cache: bundler
script:
  - "travis_retry bundle exec rake default --trace"
language: ruby
jdk: oraclejdk8
rvm:
  - 2.2.4
  - 2.3.1
  - jruby-9.0.5.0
env:
  global:
    - JRUBY_OPTS="-J-Xmx1280m -Xcompile.invokedynamic=false -J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-noverify -Xcompile.mode=OFF"
    - NEO4J_VERSION=3.1.0
  matrix:
    - NEO4J_URL="http://localhost:7474"
matrix:
  include:
    - rvm: 2.3.1
      jdk:
      install:
      script: "bundle exec rubocop"
      env: "RUBOCOP=true"
